/gps_slam_converter:
  ros__parameters:
    slam_map_width: 1238
    slam_map_height: 765
    intersection_start_point_lon: 128.858009083
    intersection_start_point_lat: 35.157430158
    intersection_end_point_lon: 128.858870603
    intersection_end_point_lat: 35.158056682
    std_point_slamX1: 415
    std_point_slamY1: 235
    std_point_slamX2: 1210
    std_point_slamY2: 541
    std_point_lon1: 128.8579836
    std_point_lat1: 35.1576298
    std_point_lon2: 128.858333
    std_point_lat2: 35.15818
    range_from_x: 0.0
    range_to_x: 0.0
    range_from_y: 0.0
    range_to_y: 0.0
    degree4th: 0.0
    degree3rd: 0.001016235
    degree2nd: -0.085948519
    degree1st: 2.589154097
    y_intercept: 1.285885402
    std_height: 6.13
